<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $table = 'category';
    protected $fillable = ["name",'icon'];

    public function foods(){
        return $this->hasMany(Food::class,"category_id");
    }

    public function toArray()
    {
        return [
            'id'=>$this->__get("id"),
            'name'=>$this->__get("name"),
            'icon'=>$this->__get("icon")
        ]; // TODO: Change the autogenerated stub
    }
}
