<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Food extends Model
{
    use HasFactory;

    protected $table = 'food';
    protected $fillable = ['name','image','description','price','category_id'];

    public function toArray()
    {
        return [
            'id'=>$this->__get("id"),
            'name'=>$this->__get("name"),
            'image'=>$this->__get("image"),
            'description'=>$this->__get("description"),
            'price'=>$this->__get("price")
        ]; // TODO: Change the autogenerated stub
    }
}
